 language: android
 jdk: oraclejdk8
 
 env:
   global:
    - ANDROID_API_LEVEL=26
    - EMULATOR_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.1.1
    - ANDROID_ABI=armeabi-v7a
 
 
 android:
   components:
     - build-tools-$ANDROID_BUILD_TOOLS_VERSION
     - android-$EMULATOR_API_LEVEL
     - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
 
 
 before_install:
   - yes | sdkmanager "platforms;android-27"